---
- name: "Install PLUGIN | verify plugin names"
  ansible.builtin.assert:
    that:
      - plugin_install_names != ""
    fail_msg: "Plugin names and versions must be provided in the format 'plugin1,plugin2' and 'version1,version2'"
  tags: install_plugin

- name: "Install PLUGIN | verify {{ plugin_install_names }} is not already installed"
  community.docker.docker_container_exec:
    container: "{{ wordpress_container }}"
    argv:
      - /bin/sh
      - -c
      - "wp plugin is-installed {{ plugin_install_names }} --allow-root"
  register: plugin_check
  failed_when: plugin_check.rc == 0
  tags: install_plugin

  - name: "Install PLUGIN | Verify if field version is provided"
    community.docker.docker_container_exec:
      container: "{{ wordpress_container }}"
      argv:
        - /bin/sh
        - -c
        - "wp plugin install  {{ plugin_install_names }} --field=version  --allow-root"
  register: plugin_version_check
  failed_when: plugin_version_check.rc != 0
  tags: install_plugin

- name: "Install PLUGIN | actual status of plugin installation"
  ansible.builtin.debug:
    msg: "Plugin {{ plugin_install_names }} {% if _already_installed == 0 %} is already installed with version {{ plugin_version_check.stdout }} {% else %} is not installed and will be installed now {% endif %}"
  tags: install_plugin

- name: "Install PLUGIN | Define if action is necessary"
  ansible.builtin.set_fact:
    _already_installed: "{{ plugin_check.rc != 0  or ( plugin_version_check.rc | length > 0  and _install_version.stdout  | trim == plugin_version_check.stdout ) }}"
  tags: install_plugin

- name: "Install PLUGIN | Define if action is not necessary"
  ansible.builtin.set_fact:
    _install_needed: "{{ not _already_installed }}"
  tags: install_plugin


# installation

- name: "Install PLUGIN | Install plugin {{ plugin_install_names }} with version {{ plugin_install_versions }}"
  community.docker.docker_container_exec:
    container: "{{ wordpress_container }}"
    argv:
      - /bin/sh
      - -c
      - "wp plugin install {{ plugin_install_names }} --version={{ plugin_install_versions }} --allow-root"
  when: _install_needed
  tags: install_plugin










