---
# tasks file for wordpress_ops
- name: "Include backup db tasks"
  include_tasks: backup_db.yml
  tags: backup_db

- name: "Include backup files tasks"
  include_tasks: backup_files.yml
  tags: backup_files

- name: "Include install plugin tasks"
  include_tasks: install_plugin.yml
  tags: install_plugin